[package]
name = "app"
version = "0.1.1"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc.13", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.0.0-rc.17", features = [] }
tauri-plugin-log = "2.0.0-rc"
sysinfo = "0.35"
jwalk = "0.9.0"
trash = "5.2.3"
dirs = "6.0.0"
xxhash-rust = { version = "0.8.18", features = ["xxh3"] }
tauri-plugin-dialog = "2.0.0-rc"
rayon = "1.10"
tauri-plugin-updater = "2.0.0-beta.0"
tauri-plugin-process = "2.0.0-beta.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
